name: Scrape

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/10 * * * *'
env:
  SENDING_EMAIL: ${{ secrets.SENDING_EMAIL }}
  RECEIVING_EMAIL: ${{ secrets.RECEIVING_EMAIL }}
  SENDING_EMAIL_PASSWORD: ${{ secrets.SENDING_EMAIL_PASSWORD }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
        python-version: '3.x'
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: run module
      run: python3 car_notify/scraper.py
    - name: Commit changes
      run: |
        git config --global user.email "${{ secrets.USER_EMAIL }}"
        git config --global user.name "${{ secrets.USER_USERNAME }}"
        git config --global user.password "${{ secrets.EMAIL_PWD }}" 
        git add .
        git commit -m "Auto updating urls.txt" | exit 0
    - name: push code to master
      run: |
        git fetch origin master
        git pull origin master
        git merge
        git push origin HEAD:master 
